### ISSUE TITLE
Add caching using sqlite3 database

### ISSUE THREAD

**Issue by Alwoch** [WikiMovimentoBrasil/deadlinkchecker#21]
### Description

A cache to be set up using sqlite3 database such that when a link is provided in the query params, Its queried in the database and the result is returned.

### Tasks:

- [ ] Write a function that checks the database for the existence of the link in the database and if it exists, return the result in the database
- [ ] Add the link to the database if it does not exist
- [ ] Dynamically clear links that have lasted more than 24 hours in the database
